export const CARDS = [
  {
    id: 0,
    name: "Ace Clubs",
    image: "assets/images/AC.jpg",
    value: 1,
  },
  {
    id: 1,
    name: "Ace Diamonds",
    image: "assets/images/AD.jpg",
    value: 1,
  },
  {
    id: 2,
    name: "Ace Hearts",
    image: "assets/images/2H.jpg",
    value: 1,
  },
  {
    id: 3,
    name: "Ace Spades",
    image: "assets/images/2S.jpg",
    value: 1,
  },
  {
    id: 4,
    name: "2 Clubs",
    image: "assets/images/2C.jpg",
    value: 2,
  },
  {
    id: 5,
    name: "2 Diamonds",
    image: "assets/images/2D.jpg",
    value: 2,
  },
  {
    id: 6,
    name: "2 Hearts",
    image: "assets/images/2H.jpg",
    value: 2,
  },
  {
    id: 7,
    name: "2 Spades",
    image: "assets/images/2S.jpg",
    value: 2,
  },
  {
    id: 8,
    name: "3 Clubs",
    image: "assets/images/2S.jpg",
    value: 3,
  },
  {
    id: 9,
    name: "3 Spades",
    image: "assets/images/3C.jpg",
    value: 3,
  },
  {
    id: 10,
    name: "3 Spades",
    image: "assets/images/3D.jpg",
    value: 3,
  },
  {
    id: 11,
    name: "3 Spades",
    image: "assets/images/3H.jpg",
    value: 3,
  },
  {
    id: 12,
    name: "4 Spades",
    image: "assets/images/3S.jpg",
    value: 4,
  },
  {
    id: 13,
    name: "4 Spades",
    image: "assets/images/4C.jpg",
    value: 4,
  },
  {
    id: 14,
    name: "4 Spades",
    image: "assets/images/4D.jpg",
    value: 4,
  },
  {
    id: 15,
    name: "3 Spades",
    image: "assets/images/4H.jpg",
    value: 4,
  },
  {
    id: 16,
    name: "4 Spades",
    image: "assets/images/4S.jpg",
    value: 4,
  },
  {
    id: 16,
    name: "5 Clubs",
    image: "assets/images/5C.jpg",
    value: 5,
  },
  {
    id: 17,
    name: "5 Diamonds",
    image: "assets/images/5D.jpg",
    value: 5,
  },
  {
    id: 18,
    name: "5 Hearts",
    image: "assets/images/5H.jpg",
    value: 5,
  },
  {
    id: 19,
    name: "5 Spades",
    image: "assets/images/5S.jpg",
    value: 5,
  },
  {
    id: 20,
    name: "6 Clubs",
    image: "assets/images/6C.jpg",
    value: 6,
  },
  {
    id: 21,
    name: "6 Diamonds",
    image: "assets/images/6D.jpg",
    value: 6,
  },
  {
    id: 22,
    name: "6 Hearts",
    image: "assets/images/6H.jpg",
    value: 6,
  },
  {
    id: 23,
    name: "6 Spades",
    image: "assets/images/6S.jpg",
    value: 6,
  },
  {
    id: 24,
    name: "7 Clubs",
    image: "assets/images/7C.jpg",
    value: 7,
  },
  {
    id: 25,
    name: "7 Diamonds",
    image: "assets/images/7D.jpg",
    value: 7,
  },
  {
    id: 26,
    name: "7 Hearts",
    image: "assets/images/7H.jpg",
    value: 7,
  },
  {
    id: 27,
    name: "7 Spades",
    image: "assets/images/7S.jpg",
    value: 7,
  },
  {
    id: 28,
    name: "8 Clubs",
    image: "assets/images/8C.jpg",
    value: 8,
  },
  {
    id: 29,
    name: "8 Diamonds",
    image: "assets/images/8D.jpg",
    value: 8,
  },
  {
    id: 30,
    name: "8 Hearts",
    image: "assets/images/8H.jpg",
    value: 8,
  },
  {
    id: 31,
    name: "8 Spades",
    image: "assets/images/8S.jpg",
    value: 8,
  },
  {
    id: 32,
    name: "9 Clubs",
    image: "assets/images/9C.jpg",
    value: 9,
  },
  {
    id: 33,
    name: "9 Diamonds",
    image: "assets/images/9D.jpg",
    value: 9,
  },
  {
    id: 34,
    name: "9 Hearts",
    image: "assets/images/9H.jpg",
    value: 9,
  },
  {
    id: 35,
    name: "9 Spades",
    image: "assets/images/9S.jpg",
    value: 9,
  },
  {
    id: 36,
    name: "10 Clubs",
    image: "assets/images/10C.jpg",
    value: 10,
  },
  {
    id: 37,
    name: "10 Diamonds",
    image: "assets/images/10D.jpg",
    value: 10,
  },
  {
    id: 38,
    name: "10 Hearts",
    image: "assets/images/10H.jpg",
    value: 10,
  },
  {
    id: 39,
    name: "10 Spades",
    image: "assets/images/10S.jpg",
    value: 10,
  },
  {
    id: 40,
    name: "Jack Clubs",
    image: "assets/images/JC.jpg",
    value: 11,
  },
  {
    id: 41,
    name: "Jack Diamonds",
    image: "assets/images/JD.jpg",
    value: 11,
  },
  {
    id: 42,
    name: "Jack Hearts",
    image: "assets/images/JH.jpg",
    value: 11,
  },
  {
    id: 43,
    name: "Jack Spades",
    image: "assets/images/JS.jpg",
    value: 11,
  },
  {
    id: 44,
    name: "Queen Clubs",
    image: "assets/images/QC.jpg",
    value: 12,
  },
  {
    id: 45,
    name: "Queen Diamonds",
    image: "assets/images/QD.jpg",
    value: 12,
  },
  {
    id: 46,
    name: "Queen Hearts",
    image: "assets/images/QH.jpg",
    value: 12,
  },
  {
    id: 47,
    name: "Queen Spades",
    image: "assets/images/QS.jpg",
    value: 12,
  },
  {
    id: 48,
    name: "King Clubs",
    image: "assets/images/KC.jpg",
    value: 13,
  },
  {
    id: 49,
    name: "King Diamonds",
    image: "assets/images/KD.jpg",
    value: 13,
  },
  {
    id: 50,
    name: "King Hearts",
    image: "assets/images/KH.jpg",
    value: 13,
  },
  {
    id: 51,
    name: "King Spades",
    image: "assets/images/KS.jpg",
    value: 13,
  },
];
